services:
  ai-agent:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:8000" # API/web interface
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=DEBUG
    command: sh -c 'echo Y | make dev'
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - .git/
            - node_modules/
            - __pycache__/
            - "*.pyc"

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./:/app
    ports:
      - "8888:8888" # Jupyter Notebook
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: make jupyter
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - .git/
            - node_modules/
            - __pycache__/
            - "*.pyc"
