hair_diagno_generation:
  description: "1. PRIMERO: analiza la imagen {image}.

    3. TERCERO: Estructura el diagnóstico en el formato JSON indicado en el expected_output, e incluye la URL pública retornada por la herramienta de upload.

    Es OBLIGATORIO que uses AMBAS herramientas en este orden. DEBES DEVOLVER UN JSON VÁLIDO según el formato especificado."
  expected_output: |
    ```json
    {
      "cliente": {
        "fecha_diagnostico": "YYYY-MM-DD"
      },
      "cabello": {
        "grosor": "fino|normal|grueso|muy_fino",
        "longitud": "muy_corto|corto|melena_corta|melena_media|melena_larga",
        "altura_tono": {
          "valor": 1-10,
          "descripcion": "descripción detallada del tono"
        },
        "canas": {
          "porcentaje": 0|10|25|50|75|100,
          "descripcion": "descripción de distribución de canas"
        },
        "matiz": "dorado|ceniza|cobrizo|rojizo",
        "textura": "liso|ondulado|rizado|crespo",
        "alteraciones": {
          "mechas": true|false,
          "tecnica_usada": "nombre de la técnica si aplica",
          "porosidad": {
            "minima": 1-5,
            "maxima": 1-5,
            "descripcion": "descripción de la porosidad"
          },
          "tratamientos": {
            "planchado": true|false,
            "lisado_quimico": true|false,
            "moldeado": true|false,
            "decolorado": true|false,
            "otro": "descripción si aplica"
          }
        },
        "analisis_color": {
          "raices": "descripción del color en raíces",
          "medios": "descripción del color en medios",
          "puntas": "descripción del color en puntas"
        },
        "condicion_general": "descripción general de la condición del cabello"
      },
      "imagen_url": "URL de la imagen analizada",
      "observaciones": "observaciones adicionales importantes"
    }
    ```

color_suggestion_generation:
  description: "Basándote en el diagnóstico capilar previo, debes:

    1. PRIMERO: Analiza la imagen {image}
    3. TERCERO: A partir de ambos análisis (el diagnóstico previo y tu análisis directo),
    formula una receta de coloración profesional detallada.

    Es OBLIGATORIO que uses la herramienta con el valor correcto de {image}.
    DEBES DEVOLVER UN JSON VÁLIDO según el formato especificado en expected_output."

  expected_output: |
    ```json
    {
      "coloracion": {
        "fecha": "YYYY-MM-DD",
        "formulacion": {
          "nombre_mezcla": "nombre descriptivo de la mezcla",
          "tipo_mezcla": "tipo de mezcla recomendada",
          "marca": "marca recomendada",
          "grama": "cantidad total en gramos",
          "componentes": [
            {
              "color": "código del color 1",
              "gramos": "cantidad en gramos"
            },
            {
              "color": "código del color 2",
              "gramos": "cantidad en gramos"
            }
          ],
          "oxidante": {
            "volumen": "10|20|30|40",
            "gramos_ml": "cantidad en gramos o ml"
          },
          "tiempo_exposicion": "tiempo en minutos"
        },
        "aplicacion": {
          "raices": {
            "color": "color aplicado raíces",
            "porcentaje_porosidad": 1-5
          },
          "medios": {
            "color": "color aplicado medios",
            "porcentaje_porosidad": 1-5
          },
          "puntas": {
            "color": "color aplicado puntas",
            "porcentaje_porosidad": 1-5
          }
        },
        "color_obtenido": "descripción del color resultante esperado",
        "reequilibrio_ph": {
          "champu_acido": true|false,
          "acondicionador": true|false,
          "plex": true|false,
          "otro": "descripción si aplica"
        },
        "recomendaciones": [
          "recomendación de cuidado 1",
          "recomendación de cuidado 2",
          "recomendación de cuidado 3"
        ],
        "mantenimiento": {
          "frecuencia": "cada X semanas",
          "productos_recomendados": [
            "producto 1",
            "producto 2"
          ]
        }
      },
      "observaciones": "observaciones adicionales importantes"
    }
    ```

    ## Cuidados Posteriores a la Aplicación:
    - [recomendación 1]
    - [recomendación 2]
    - [recomendación 3]

    ## Plan de Mantenimiento:
    - [plan 1]
    - [plan 2]
    - [plan 3]

    ## Resultado Esperado:
    [descripción detallada del resultado]

    ## Explicación Técnica:
    [explicación detallada del razonamiento detrás de la formulación, apoyándote en el análisis previo y los detalles técnicos observados]"
