analize_cashflow:
  description: >
    Analiza la siguiente información financiera del usuario:
    <text>
    {prompt}
    </text>
    Tu objetivo es entender cuánto dinero puede invertir la persona de forma segura cada mes.
  expected_output: >
    Un resumen claro que muestre:
    - Cuánto dinero gana al mes
    - Cuáles son sus gastos fijos
    - Cuánto dinero le queda disponible para invertir
    - Una explicación sencilla de cómo se llegó a esa cantidad

find_tickers:
  description: >
    Encuentra las 3 mejores empresas para invertir según:
    - El nivel de riesgo que la persona quiere asumir (bajo, medio, alto, muy alto)
    - La cantidad de dinero que puede invertir
    Extrae esta información del siguiente texto:
    <text>
    {prompt}
    </text>
  expected_output: >
    Una lista de 3 empresas recomendadas para invertir, explicando:
    - Por qué cada empresa es una buena opción
    - Qué nivel de riesgo tiene cada una
    - Cuánto dinero se recomienda invertir en cada una

generate_investment_scenarios:
  description: >
    Crea diferentes escenarios de inversión que muestren cómo podría crecer el dinero del usuario.
    Usa la herramienta ActionsDataTool para analizar acciones y CryptoDataTool para criptomonedas.
    Crea al menos dos escenarios:
    1. Un escenario más conservador con acciones
    2. Un escenario más arriesgado con criptomonedas
  expected_output: >
    Escenarios de inversión detallados con el siguiente formato:
    <example>
    - Escenario Conservador:
      - Riesgo: Bajo
      - Dinero a invertir: 1000 euros
      - Tiempo: 1 año
      - Rentabilidad esperada: 5%
      - Tipo de inversión: Acciones
      - Empresa: Ejemplo S.A.
      - Ingreso mensual estimado: 50 euros
    - Escenario Arriesgado:
      - Riesgo: Alto
      - Dinero a invertir: 1000 euros
      - Tiempo: 1 año
      - Rentabilidad esperada: 15%
      - Tipo de inversión: Criptomonedas
      - Moneda: Bitcoin
      - Ingreso mensual estimado: 100 euros
    </example>

optimizated_investment_scenarios:
  description: >
    Crea un plan de inversión personalizado basado en:
    - El análisis del flujo de efectivo del usuario
    - Los escenarios de inversión generados
    - El perfil de riesgo del usuario
    El objetivo es crear un plan que:
    - Se ajuste a la situación financiera del usuario
    - Equilibre riesgo y rentabilidad
    - Sea fácil de entender y seguir
    - Incluya recomendaciones prácticas
  expected_output: >
    Un plan de inversión completo que incluya:
    1. Resumen de la situación financiera
    2. Diferentes opciones de inversión con:
       - Nivel de riesgo (Bajo/Medio/Alto/Muy Alto)
       - Cantidad recomendada a invertir
       - Tiempo recomendado
       - Rentabilidad esperada
       - Ingresos mensuales estimados
    3. Explicación clara de cada opción
    4. Comparación entre las diferentes opciones
    5. Recomendaciones finales
    6. Consejos prácticos para empezar
    7. Preguntas frecuentes y respuestas
    8. Todo explicado en español de forma sencilla