analize_cashflow:
  description: >
    Analize the cashflow of the following text:
    <text>
    {prompt}
    </text>
  expected_output: >
    Returns the avaible quantity to invest from the user's cashflow

find_tickers:
  description: >
    Find the tickers of the 3 best companies to invest in based on the risk level and the investment amount. The risk level will be very_high, high, medium, low.
    You will extract the risk level and the investment amount from the following text:
    <text>
    {prompt}
    </text>
  expected_output: >
    A list of 3 tickers of the best companies to invest in based on the risk level and the investment amount.

generate_investment_scenarios:
  description: >
    Generate investment scenarios, you need to pass the tickers to ActionsDataTool, and generate another crypto-scenario with the tool CryptoDataTool(This scenario gonna be risk because the volatibity of cryptos)
  expected_output: >
    Returns the investment scenarios with the following format:
    <example>
    - Scenario 1:
      - Risk: High
      - Quantity of money to invest: 1000
      - Time to invest: 1 year
      - Aproximate return: 10%
      - Dividend yield: 2%(if applicable)
      - Investment type: Crypto
      - Name of the investment: Bitcoin
      - Monthly income: 100 euros
    - Scenario 2:
      - Risk: Low
      - Quantity of money to invest: 1000
      - Time to invest: 1 year
      - Aproximate return: 5%
      - Dividend yield: 1%(if applicable)
      - Investment type: Actions
      - Name of the investment: Company X
      - Monthly income: 100 euros
    </example>

optimizated_investment_scenarios:
  description: >
    Optimize the investment scenarios based on the output of the analize_cashflow task and the investment scenarios generated in the generate_investment_scenarios task, generates a report
    in format markdown,
  expected_output: >
    Returns the optimized investment scenarios in spanish in the format markdown, doing table with the following columns:
    - Scenario
    - Risk
    - Quantity of money to invest
    - Time to invest
    - Aproximate return
    - Dividend yield
    - Total return (return + dividend yield in percentage)
    - Conversion of the original quantity of money to invest with the total return
    - Investment type
    - Name of the investment
    - Monthly income
    - URLs to check values of each invest, for the tickers, you can put https://finance.yahoo.com/quote/(name of the ticker)/ and for cryptos https://coinmarketcap.com/es/currencies/(name of crypto)/
    Here you have an example of the output you need to do
    <example>
    # 🧾 Informe de Escenarios de Inversión Optimizada

    Este informe presenta **cuatro escenarios de inversión**, cada uno con un nivel de riesgo distinto y una estimación de rentabilidad al cabo de **1 año**, utilizando una inversión inicial de **1000 euros** en cada caso.

    El objetivo es mostrar posibles caminos para alcanzar una meta de **2500 euros en un plazo de 24 meses**, combinando diferentes tipos de inversiones.

    ---

    ## 📊 Comparativa de Escenarios

    | Escenario | Nivel de Riesgo | Monto a Invertir | Plazo | Rentabilidad Estimada | Dividendos Estimados | Rentabilidad Total (%) | Monto Final Estimado | Tipo de Inversión | Nombre del Activo                     | Ingreso Mensual Estimado | Enlace de Referencia |
    |-----------|------------------|------------------|--------|------------------------|-----------------------|-------------------------|------------------------|-------------------|--------------------------------------|---------------------------|------------------------|
    | 1         | Alto             | 1000 €           | 1 año  | 20%                    | N/A                   | 20%                     | 1200 €                 | Criptomoneda      | Dogecoin                             | 100 €                     | [Dogecoin](https://coinmarketcap.com/es/currencies/dogecoin/) |
    | 2         | Medio            | 1000 €           | 1 año  | 10%                    | 2%                    | 12%                     | 1120 €                 | Acción            | Morgan Stanley (MS)                  | 100 €                     | [MS](https://finance.yahoo.com/quote/MS/) |
    | 3         | Medio            | 1000 €           | 1 año  | 8%                     | 1.5%                  | 9.5%                    | 1095 €                 | Acción            | Merck & Co. (MRK)                    | 100 €                     | [MRK](https://finance.yahoo.com/quote/MRK/) |
    | 4         | Medio            | 1000 €           | 1 año  | 9%                     | 1.75%                 | 10.75%                  | 1107,5 €               | Acción            | PNC Financial Services Group (PNC)   | 100 €                     | [PNC](https://finance.yahoo.com/quote/PNC/) |

    ---

    ## 📌 Resumen General

    Los escenarios presentados muestran distintas opciones de inversión utilizando una base de 1000 euros durante 12 meses. La elección de cada escenario depende del nivel de riesgo que estés dispuesto a asumir:

    - **Escenario 1**: Alta rentabilidad estimada (20%), pero también alto riesgo, ya que se trata de una criptomoneda (Dogecoin).
    - **Escenarios 2, 3 y 4**: Alternativas con riesgo medio y rendimientos más moderados. Están basadas en acciones de empresas reconocidas, con retornos que combinan crecimiento del valor y dividendos.

    Estas opciones permiten **diversificar** tu cartera de inversión, algo útil para **reducir el riesgo general** y **aumentar el potencial de retorno**. Aunque cada escenario cubre solo un año, podrías reinvertir los resultados en el segundo año para acercarte al objetivo de 2500 euros en total.
    </example>